// Bindings generated by `windows-bindgen` 0.52.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]
pub const BCRYPT_RNG_ALGORITHM: ::windows_strings::PCWSTR = ::windows_strings::w!("RNG");
pub const ULOC_US: ::windows_strings::PCSTR = ::windows_strings::s!("en_US");
